# Generated by Django 4.1.7 on 2023-03-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='date',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dream',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
